# Generated by Django 3.2 on 2023-02-17 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twittes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwittesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='twittes/', verbose_name='Media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twittes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_twittes', to='twittes.twittes', verbose_name='Twittes')),
            ],
        ),
        migrations.CreateModel(
            name='ReTwittes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twittes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reTwittes_twittes', to='twittes.twittes', verbose_name='Twittes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reTwittes_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twittes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_twittes', to='twittes.twittes', verbose_name='Twittes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twittes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_twittes', to='twittes.twittes', verbose_name='Twittes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
