# Generated by Django 3.2 on 2023-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittes', '0002_comment_like_retwittes_twittesmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittesmedia',
            name='media',
            field=models.FileField(upload_to='twittes/', verbose_name='Media'),
        ),
    ]
